version: '3'

services:
  new_postgres:
    build: ./pg_new
    volumes:
      - ./new-data:/data
      - docker-postgres-data:/shared-data
    environment:
      - PGDATA=/data
  old_postgres:
    build: ./pg_old
    volumes:
      - ./old-data:/data
      - docker-postgres-data:/shared-data
    environment:
      - PGDATA=/data

volumes:
  docker-postgres-data:
